# Generated by Django 5.0.7 on 2025-02-27 00:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='activity_level',
            field=models.CharField(choices=[('sed', 'Sedentary'), ('lig', 'Lightly active'), ('mod', 'Moderately active'), ('ver', 'Very active'), ('ext', 'Extremely active')], default='m'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='body_fat',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
        migrations.AddField(
            model_name='customuser',
            name='date_of_birth',
            field=models.DateField(default='2000-01-01'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='goal',
            field=models.CharField(choices=[('losew', 'Lose weight'), ('gainw', 'Gain weight'), ('mainw', 'Maintain weight'), ('gainm', 'Gain muscle weight'), ('mainm', 'Maintain muscle weight')], default='mainw'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='height',
            field=models.IntegerField(default=130, validators=[django.core.validators.MinValueValidator(130), django.core.validators.MaxValueValidator(250)]),
        ),
        migrations.AddField(
            model_name='customuser',
            name='sex',
            field=models.CharField(choices=[('m', 'Male'), ('f', 'Female')], default='m'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='target',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(40), django.core.validators.MaxValueValidator(200)]),
        ),
        migrations.AddField(
            model_name='customuser',
            name='weight',
            field=models.IntegerField(default=40, validators=[django.core.validators.MinValueValidator(40), django.core.validators.MaxValueValidator(200)]),
        ),
    ]
