# Generated by Django 5.0.7 on 2025-03-01 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_weightprogresslog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WeightProgressLog',
        ),
    ]
