# Generated by Django 5.0.7 on 2025-05-08 15:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNutritionProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wght', models.FloatField(default=0)),
                ('hght', models.IntegerField(default=0)),
                ('age', models.IntegerField(default=0)),
                ('sex', models.CharField(choices=[('m', 'Male'), ('f', 'Female'), ('na', 'N/A')], default='na')),
                ('act_lvl', models.CharField(choices=[('sed', 'Sedentary'), ('lig', 'Lightly active'), ('mod', 'Moderately active'), ('ver', 'Very active'), ('ext', 'Extremely active'), ('na', 'N/A')], default='na')),
                ('lbm', models.FloatField(default=0)),
                ('bmr', models.FloatField(default=0)),
                ('tdee', models.FloatField(default=0)),
                ('goal_cal', models.FloatField(default=0)),
                ('goal_car', models.FloatField(default=0)),
                ('goal_pro', models.FloatField(default=0)),
                ('goal_fat', models.FloatField(default=0)),
                ('now_cal', models.FloatField(default=0)),
                ('now_car', models.FloatField(default=0)),
                ('now_pro', models.FloatField(default=0)),
                ('now_fat', models.FloatField(default=0)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
