# Generated by Django 5.0.7 on 2025-05-10 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usernutritionprofile',
            name='now_cal',
        ),
        migrations.RemoveField(
            model_name='usernutritionprofile',
            name='now_car',
        ),
        migrations.RemoveField(
            model_name='usernutritionprofile',
            name='now_fat',
        ),
        migrations.RemoveField(
            model_name='usernutritionprofile',
            name='now_pro',
        ),
    ]
