# Generated by Django 5.0.7 on 2025-03-03 14:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MealLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('meal', models.JSONField()),
                ('logged', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProgressLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity_level', models.CharField(choices=[('sed', 'Sedentary'), ('lig', 'Lightly active'), ('mod', 'Moderately active'), ('ver', 'Very active'), ('ext', 'Extremely active')], default='sed', max_length=15)),
                ('goal', models.CharField(choices=[('losew', 'Lose weight'), ('gainw', 'Gain weight'), ('mainw', 'Maintain weight'), ('gainm', 'Gain muscle weight'), ('mainm', 'Maintain muscle weight')], default='mainw', max_length=15)),
                ('meal_logs', models.JSONField()),
                ('target_cals', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('target_carbs', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('target_prot', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('target_fats', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('real_cals', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('real_carbs', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('real_prot', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('real_fats', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('logged_weight', models.DecimalField(decimal_places=1, max_digits=4, null=True)),
                ('approx_delta_weight', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('approx_delta_fat', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('approx_delta_muscle', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('logged', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
