# Generated by Django 5.0.7 on 2025-03-06 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0002_meallog_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meallog',
            name='name',
        ),
    ]
