# Generated by Django 5.0.7 on 2025-04-14 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0004_alter_meallog_meal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progresslog',
            name='meal_logs',
            field=models.JSONField(default=dict),
        ),
    ]
