# Generated by Django 5.0.7 on 2025-05-08 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0006_rename_meal_meallog_foods'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProgressLog',
        ),
    ]
