# Generated by Django 5.0.7 on 2025-05-08 15:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSocialProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_flws', models.IntegerField(default=0, null=True)),
                ('count_flwrs', models.IntegerField(default=0, null=True)),
                ('count_psts', models.IntegerField(default=0, null=True)),
                ('count_rcps', models.IntegerField(default=0, null=True)),
                ('count_like', models.IntegerField(default=0, null=True)),
                ('bio', models.TextField(blank=True)),
                ('pfp', models.ImageField(blank=True, null=True, upload_to='pfps/')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
