# Generated by Django 5.0.7 on 2025-05-09 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_follow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersocialprofile',
            name='count_flwrs',
        ),
        migrations.RemoveField(
            model_name='usersocialprofile',
            name='count_flws',
        ),
        migrations.RemoveField(
            model_name='usersocialprofile',
            name='count_like',
        ),
        migrations.RemoveField(
            model_name='usersocialprofile',
            name='count_psts',
        ),
        migrations.RemoveField(
            model_name='usersocialprofile',
            name='count_rcps',
        ),
    ]
