# Generated by Django 5.0.7 on 2025-05-13 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='fooditemnutrient',
            unique_together={('food', 'nutrient')},
        ),
    ]
