# Generated by Django 5.0.7 on 2025-05-15 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_alter_fooditemnutrient_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='fooditemcategory',
            unique_together={('food', 'category')},
        ),
        migrations.AlterUniqueTogether(
            name='fooditemcuisine',
            unique_together={('food', 'cuisine')},
        ),
    ]
