# Generated by Django 5.0.7 on 2025-05-15 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_fooditemchildren'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FoodItemChildren',
        ),
    ]
