# Generated by Django 5.0.7 on 2025-05-15 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0006_fooditemchildren'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FoodItemChildren',
            new_name='FoodItemChild',
        ),
    ]
