# Generated by Django 5.0.7 on 2025-06-13 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0007_rename_fooditemchildren_fooditemchild'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fooditemchild',
            old_name='quantity',
            new_name='amount',
        ),
        migrations.AlterUniqueTogether(
            name='fooditemchild',
            unique_together={('parent', 'child')},
        ),
    ]
