# Generated by Django 5.0.7 on 2025-06-15 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0008_rename_quantity_fooditemchild_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutrient',
            name='name',
            field=models.CharField(unique=True),
        ),
    ]
