# Generated by Django 5.0.7 on 2025-06-15 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0010_alter_nutrient_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='nutrient',
            unique_together={('name', 'unit')},
        ),
    ]
