# Generated by Django 5.0.7 on 2025-06-22 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0012_alter_foodcategory_name_alter_foodcuisine_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FoodItemChild',
            new_name='FoodItemComposition',
        ),
    ]
